import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { Loader2, Save, Download } from "lucide-react";

interface ProfitSharingResults {
  totalProfit: string;
  investorSharePercentage: string;
  partnerSharePercentage: string;
  investorAmount: string;
  partnerAmount: string;
}

export function ProfitSharingCalculator() {
  const { toast } = useToast();
  const [inputs, setInputs] = useState({
    totalProfit: "",
    investorSharePercentage: "",
    partnerSharePercentage: "",
  });
  const [results, setResults] = useState<ProfitSharingResults | null>(null);
  const [email, setEmail] = useState("");

  const calculateMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest("/api/calculators/calculate", {
        method: "POST",
        body: JSON.stringify({
          type: "profit-sharing",
          inputs,
        }),
        headers: { "Content-Type": "application/json" },
      });
      return response.data;
    },
    onSuccess: (data) => {
      setResults(data);
    },
    onError: () => {
      toast({
        title: "Calculation Failed",
        description: "Please check your inputs and try again.",
        variant: "destructive",
      });
    },
  });

  const saveMutation = useMutation({
    mutationFn: async () => {
      await apiRequest("/api/calculators/save", {
        method: "POST",
        body: JSON.stringify({
          calculatorType: "profit-sharing",
          inputs: JSON.stringify(inputs),
          results: JSON.stringify(results),
          email: email || undefined,
          saved: true,
        }),
        headers: { "Content-Type": "application/json" },
      });
    },
    onSuccess: () => {
      toast({
        title: "Saved Successfully",
        description: "Your calculation has been saved.",
      });
    },
  });

  const handleCalculate = (e: React.FormEvent) => {
    e.preventDefault();
    const total = Number(inputs.investorSharePercentage) + Number(inputs.partnerSharePercentage);
    if (total !== 100) {
      toast({
        title: "Invalid Shares",
        description: "The total of both shares must equal 100%",
        variant: "destructive",
      });
      return;
    }
    calculateMutation.mutate();
  };

  const handleDownload = () => {
    if (!results) return;
    const content = `
Profit Sharing (Musharakah) Calculation
========================================

Total Profit: AED ${results.totalProfit}
Investor Share: ${results.investorSharePercentage} = AED ${results.investorAmount}
Partner Share: ${results.partnerSharePercentage} = AED ${results.partnerAmount}

Generated by iamfasih.com/calculators
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "profit-sharing-calculation.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <form onSubmit={handleCalculate} className="space-y-4">
        <div className="grid md:grid-cols-3 gap-4">
          <div className="space-y-2">
            <Label htmlFor="totalProfit">Total Profit (AED)</Label>
            <Input
              id="totalProfit"
              type="number"
              step="0.01"
              required
              value={inputs.totalProfit}
              onChange={(e) => setInputs({ ...inputs, totalProfit: e.target.value })}
              placeholder="100000"
              data-testid="input-total-profit"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="investorSharePercentage">Investor Share (%)</Label>
            <Input
              id="investorSharePercentage"
              type="number"
              step="0.1"
              required
              min="0"
              max="100"
              value={inputs.investorSharePercentage}
              onChange={(e) => setInputs({ ...inputs, investorSharePercentage: e.target.value })}
              placeholder="60"
              data-testid="input-investor-share"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="partnerSharePercentage">Partner Share (%)</Label>
            <Input
              id="partnerSharePercentage"
              type="number"
              step="0.1"
              required
              min="0"
              max="100"
              value={inputs.partnerSharePercentage}
              onChange={(e) => setInputs({ ...inputs, partnerSharePercentage: e.target.value })}
              placeholder="40"
              data-testid="input-partner-share"
            />
          </div>
        </div>

        <div className="text-sm text-muted-foreground">
          Note: The total of both shares must equal 100%
        </div>

        <Button type="submit" disabled={calculateMutation.isPending} className="w-full md:w-auto" data-testid="button-calculate">
          {calculateMutation.isPending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Calculating...
            </>
          ) : (
            "Calculate"
          )}
        </Button>
      </form>

      {results && (
        <Card className="p-6 space-y-6" data-testid="card-results">
          <div>
            <h3 className="text-2xl font-bold mb-4">Profit Distribution Summary</h3>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">Total Profit</p>
                <p className="text-2xl font-bold">AED {results.totalProfit}</p>
              </div>
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">&nbsp;</p>
                <p className="text-2xl font-bold">&nbsp;</p>
              </div>
              <div className="p-4 bg-primary/10 rounded-lg border-2 border-primary">
                <p className="text-sm text-muted-foreground">Investor ({results.investorSharePercentage})</p>
                <p className="text-2xl font-bold text-primary">AED {results.investorAmount}</p>
              </div>
              <div className="p-4 bg-green-500/10 rounded-lg border-2 border-green-500">
                <p className="text-sm text-muted-foreground">Partner ({results.partnerSharePercentage})</p>
                <p className="text-2xl font-bold text-green-500">AED {results.partnerAmount}</p>
              </div>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <div className="flex-1">
              <Input
                type="email"
                placeholder="Enter email to save results"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                data-testid="input-email-save"
              />
            </div>
            <Button onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending} data-testid="button-save">
              <Save className="mr-2 h-4 w-4" />
              Save Results
            </Button>
            <Button variant="outline" onClick={handleDownload} data-testid="button-download">
              <Download className="mr-2 h-4 w-4" />
              Download
            </Button>
          </div>
        </Card>
      )}
    </div>
  );
}
