import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { Loader2, Save, Download } from "lucide-react";

interface ROIResults {
  initialInvestment: string;
  returns: string;
  netProfit: string;
  roi: string;
  annualizedROI: string;
  timeperiodMonths: number;
}

export function ROICalculator() {
  const { toast } = useToast();
  const [inputs, setInputs] = useState({
    initialInvestment: "",
    returns: "",
    timeperiodMonths: "",
  });
  const [results, setResults] = useState<ROIResults | null>(null);
  const [email, setEmail] = useState("");

  const calculateMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest("/api/calculators/calculate", {
        method: "POST",
        body: JSON.stringify({
          type: "roi",
          inputs,
        }),
        headers: { "Content-Type": "application/json" },
      });
      return response.data;
    },
    onSuccess: (data) => {
      setResults(data);
    },
    onError: () => {
      toast({
        title: "Calculation Failed",
        description: "Please check your inputs and try again.",
        variant: "destructive",
      });
    },
  });

  const saveMutation = useMutation({
    mutationFn: async () => {
      await apiRequest("/api/calculators/save", {
        method: "POST",
        body: JSON.stringify({
          calculatorType: "roi",
          inputs: JSON.stringify(inputs),
          results: JSON.stringify(results),
          email: email || undefined,
          saved: true,
        }),
        headers: { "Content-Type": "application/json" },
      });
    },
    onSuccess: () => {
      toast({
        title: "Saved Successfully",
        description: "Your calculation has been saved.",
      });
    },
  });

  const handleCalculate = (e: React.FormEvent) => {
    e.preventDefault();
    calculateMutation.mutate();
  };

  const handleDownload = () => {
    if (!results) return;
    const content = `
ROI Calculation
===============

Initial Investment: AED ${results.initialInvestment}
Total Returns: AED ${results.returns}
Net Profit: AED ${results.netProfit}
ROI: ${results.roi}
Annualized ROI: ${results.annualizedROI}
Time Period: ${results.timeperiodMonths} months

Generated by iamfasih.com/calculators
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "roi-calculation.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <form onSubmit={handleCalculate} className="space-y-4">
        <div className="grid md:grid-cols-3 gap-4">
          <div className="space-y-2">
            <Label htmlFor="initialInvestment">Initial Investment (AED)</Label>
            <Input
              id="initialInvestment"
              type="number"
              step="0.01"
              required
              value={inputs.initialInvestment}
              onChange={(e) => setInputs({ ...inputs, initialInvestment: e.target.value })}
              placeholder="100000"
              data-testid="input-initial-investment"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="returns">Total Returns (AED)</Label>
            <Input
              id="returns"
              type="number"
              step="0.01"
              required
              value={inputs.returns}
              onChange={(e) => setInputs({ ...inputs, returns: e.target.value })}
              placeholder="150000"
              data-testid="input-returns"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="timeperiodMonths">Time Period (Months)</Label>
            <Input
              id="timeperiodMonths"
              type="number"
              required
              min="1"
              value={inputs.timeperiodMonths}
              onChange={(e) => setInputs({ ...inputs, timeperiodMonths: e.target.value })}
              placeholder="12"
              data-testid="input-time-period"
            />
          </div>
        </div>

        <Button type="submit" disabled={calculateMutation.isPending} className="w-full md:w-auto" data-testid="button-calculate">
          {calculateMutation.isPending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Calculating...
            </>
          ) : (
            "Calculate ROI"
          )}
        </Button>
      </form>

      {results && (
        <Card className="p-6 space-y-6" data-testid="card-results">
          <div>
            <h3 className="text-2xl font-bold mb-4">Return on Investment Summary</h3>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">Initial Investment</p>
                <p className="text-2xl font-bold">AED {results.initialInvestment}</p>
              </div>
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">Total Returns</p>
                <p className="text-2xl font-bold">AED {results.returns}</p>
              </div>
              <div className="p-4 bg-green-500/10 rounded-lg border-2 border-green-500">
                <p className="text-sm text-muted-foreground">Net Profit</p>
                <p className="text-2xl font-bold text-green-500">AED {results.netProfit}</p>
              </div>
              <div className="p-4 bg-primary/10 rounded-lg border-2 border-primary">
                <p className="text-sm text-muted-foreground">ROI</p>
                <p className="text-2xl font-bold text-primary">{results.roi}</p>
              </div>
              <div className="p-4 bg-primary/10 rounded-lg border-2 border-primary">
                <p className="text-sm text-muted-foreground">Annualized ROI</p>
                <p className="text-2xl font-bold text-primary">{results.annualizedROI}</p>
              </div>
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">Time Period</p>
                <p className="text-2xl font-bold">{results.timeperiodMonths} months</p>
              </div>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <div className="flex-1">
              <Input
                type="email"
                placeholder="Enter email to save results"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                data-testid="input-email-save"
              />
            </div>
            <Button onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending} data-testid="button-save">
              <Save className="mr-2 h-4 w-4" />
              Save Results
            </Button>
            <Button variant="outline" onClick={handleDownload} data-testid="button-download">
              <Download className="mr-2 h-4 w-4" />
              Download
            </Button>
          </div>
        </Card>
      )}
    </div>
  );
}
