import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import { Loader2, Save, Download } from "lucide-react";

interface TakafulResults {
  sumAssured: string;
  age: number;
  term: string;
  contributionFrequency: string;
  contribution: string;
  annualContribution: string;
  totalContributions: string;
}

export function TakafulCalculator() {
  const { toast } = useToast();
  const [inputs, setInputs] = useState({
    sumAssured: "",
    age: "",
    term: "",
    contributionFrequency: "monthly",
  });
  const [results, setResults] = useState<TakafulResults | null>(null);
  const [email, setEmail] = useState("");

  const calculateMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest("/api/calculators/calculate", {
        method: "POST",
        body: JSON.stringify({
          type: "takaful",
          inputs,
        }),
        headers: { "Content-Type": "application/json" },
      });
      return response.data;
    },
    onSuccess: (data) => {
      setResults(data);
    },
    onError: () => {
      toast({
        title: "Calculation Failed",
        description: "Please check your inputs and try again.",
        variant: "destructive",
      });
    },
  });

  const saveMutation = useMutation({
    mutationFn: async () => {
      await apiRequest("/api/calculators/save", {
        method: "POST",
        body: JSON.stringify({
          calculatorType: "takaful",
          inputs: JSON.stringify(inputs),
          results: JSON.stringify(results),
          email: email || undefined,
          saved: true,
        }),
        headers: { "Content-Type": "application/json" },
      });
    },
    onSuccess: () => {
      toast({
        title: "Saved Successfully",
        description: "Your calculation has been saved.",
      });
    },
  });

  const handleCalculate = (e: React.FormEvent) => {
    e.preventDefault();
    calculateMutation.mutate();
  };

  const handleDownload = () => {
    if (!results) return;
    const content = `
Takaful (Islamic Insurance) Calculation
========================================

Sum Assured: AED ${results.sumAssured}
Age: ${results.age} years
Term: ${results.term}
Contribution Frequency: ${results.contributionFrequency}
Contribution: AED ${results.contribution}
Annual Contribution: AED ${results.annualContribution}
Total Contributions: AED ${results.totalContributions}

Generated by iamfasih.com/calculators
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "takaful-calculation.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <form onSubmit={handleCalculate} className="space-y-4">
        <div className="grid md:grid-cols-2 gap-4">
          <div className="space-y-2">
            <Label htmlFor="sumAssured">Sum Assured (AED)</Label>
            <Input
              id="sumAssured"
              type="number"
              step="0.01"
              required
              value={inputs.sumAssured}
              onChange={(e) => setInputs({ ...inputs, sumAssured: e.target.value })}
              placeholder="500000"
              data-testid="input-sum-assured"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="age">Age (years)</Label>
            <Input
              id="age"
              type="number"
              required
              min="18"
              max="70"
              value={inputs.age}
              onChange={(e) => setInputs({ ...inputs, age: e.target.value })}
              placeholder="35"
              data-testid="input-age"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="term">Term (years)</Label>
            <Input
              id="term"
              type="number"
              required
              min="1"
              max="30"
              value={inputs.term}
              onChange={(e) => setInputs({ ...inputs, term: e.target.value })}
              placeholder="20"
              data-testid="input-term"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="contributionFrequency">Contribution Frequency</Label>
            <Select
              value={inputs.contributionFrequency}
              onValueChange={(value) => setInputs({ ...inputs, contributionFrequency: value })}
            >
              <SelectTrigger id="contributionFrequency" data-testid="select-contribution-frequency">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="monthly">Monthly</SelectItem>
                <SelectItem value="quarterly">Quarterly</SelectItem>
                <SelectItem value="semi-annual">Semi-Annual</SelectItem>
                <SelectItem value="annual">Annual</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        <Button type="submit" disabled={calculateMutation.isPending} className="w-full md:w-auto" data-testid="button-calculate">
          {calculateMutation.isPending ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Calculating...
            </>
          ) : (
            "Calculate"
          )}
        </Button>
      </form>

      {results && (
        <Card className="p-6 space-y-6" data-testid="card-results">
          <div>
            <h3 className="text-2xl font-bold mb-4">Takaful Coverage Summary</h3>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">Sum Assured</p>
                <p className="text-2xl font-bold">AED {results.sumAssured}</p>
              </div>
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">Age</p>
                <p className="text-2xl font-bold">{results.age} years</p>
              </div>
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">Term</p>
                <p className="text-2xl font-bold">{results.term}</p>
              </div>
              <div className="p-4 bg-primary/10 rounded-lg border-2 border-primary">
                <p className="text-sm text-muted-foreground">Contribution</p>
                <p className="text-2xl font-bold text-primary">AED {results.contribution}</p>
              </div>
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">Annual Contribution</p>
                <p className="text-2xl font-bold">AED {results.annualContribution}</p>
              </div>
              <div className="p-4 bg-muted rounded-lg">
                <p className="text-sm text-muted-foreground">Total Contributions</p>
                <p className="text-2xl font-bold">AED {results.totalContributions}</p>
              </div>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <div className="flex-1">
              <Input
                type="email"
                placeholder="Enter email to save results"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                data-testid="input-email-save"
              />
            </div>
            <Button onClick={() => saveMutation.mutate()} disabled={saveMutation.isPending} data-testid="button-save">
              <Save className="mr-2 h-4 w-4" />
              Save Results
            </Button>
            <Button variant="outline" onClick={handleDownload} data-testid="button-download">
              <Download className="mr-2 h-4 w-4" />
              Download
            </Button>
          </div>
        </Card>
      )}
    </div>
  );
}
